nodeLinker: node-modules

# Default to npmjs for unscoped packages
npmRegistryServer: "https://registry.npmjs.org"

# Send @weroad scoped packages to GitHub Packages
npmScopes:
  weroad:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAlwaysAuth: true
